/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.19
 * Generated at: 2020-02-04 13:36:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("      <meta charset=\"UTF-8\">\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("      <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("      <title>Responsive Sticky Navbar</title>\n");
      out.write("      <link rel=\"stylesheet\" href=\"./css/header.css\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("      <script src=\"https://code.jquery.com/jquery-3.3.1.js\"></script>\n");
      out.write("      \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"wrapper\">\n");
      out.write("            <header>\n");
      out.write("                  <nav>\n");
      out.write("\n");
      out.write("<!--                         <div class=\"menu-icon\">\n");
      out.write("                              <i class=\"fa fa-bars fa-2x\"></i>\n");
      out.write("                        </div> -->\n");
      out.write("\n");
      out.write("                        <div class=\"logo\">\n");
      out.write("                              <!-- LOGO -->\n");
      out.write("                              <a class=\"center__text glitch is-glitching\" data-text=\"ENTRY\" href=\"#\"><span>ENTRY</span></a>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("\n");
      out.write("            <div class=\"menu\">\n");
      out.write("            \n");
      out.write("            \t\t<ul>\t\n");
      out.write("            \t\t\t\t\t");

            						String getSession = "";
            					
            						try{
            							getSession = (String)session.getAttribute("id");
            							if(getSession == null || getSession.equals("")){

            							}
            							else{
   								
      out.write("\t\t\t<li><a href=\"#\">Welcome ");
      out.print(getSession );
      out.write("</a></li>\n");
      out.write("   \t                            ");

            							}
            						}catch(Exception e){
            							System.out.println("Exception : " + e);
            						}
            					
      out.write("\n");
      out.write("                                    <li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("<!--                                     <li><a href=\"#\">About</a></li>\n");
      out.write("                                    <li><a href=\"#\">Blog</a></li> -->\n");
      out.write("                                    <li><a href=\"contact.jsp\">Contact</a></li>\n");
      out.write("                                    \n");
      out.write("\t                            ");
									
	                            	try{
	                            		getSession = (String)session.getAttribute("id");
	                            		if(getSession == null || getSession.equals("")){
	                            
      out.write("\t\t\t<li><a href=\"login.jsp\">Log-in</a></li>\n");
      out.write("\t                            ");

	                            		}
	                            		else{
	                            			if(getSession.equals("admin")){
                   				
      out.write("\t\t\t<li><a href=\"press.jsp\">!!! PRESS !!!</a></li>\n");
      out.write("   \t                            ");

	                            			}
	                            
      out.write("\t\t\t<li><a href=\"logout.jsp\">Log-Out</a></li>\n");
      out.write("\t                            ");

	                            		}
	                            	}catch(Exception e){
	                            		System.out.println("Exception : " + e);
	                            	}
								
								
      out.write("\n");
      out.write("                   \t</ul>\n");
      out.write("                  \n");
      out.write("            </div>\n");
      out.write("                  </nav>\n");
      out.write("            </header>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <script type=\"text/javascript\">\n");
      out.write("/* \n");
      out.write("      // Menu-toggle button\n");
      out.write("\n");
      out.write("      $(document).ready(function() {\n");
      out.write("            $(\".menu-icon\").on(\"click\", function() {\n");
      out.write("                  $(\"nav ul\").toggleClass(\"showing\");\n");
      out.write("            });\n");
      out.write("      });\n");
      out.write("      \n");
      out.write("\n");
      out.write("      // Scrolling Effect\n");
      out.write("\n");
      out.write("      $(window).on(\"scroll\", function() {\n");
      out.write("            if($(window).scrollTop()) {\n");
      out.write("                  $('nav').addClass('black');\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            else {\n");
      out.write("                  $('nav').removeClass('black');\n");
      out.write("            }\n");
      out.write("      }) */\n");
      out.write("\n");
      out.write("\n");
      out.write("      </script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
